<a href="https://colab.research.google.com/github/TranThiDieuHien/pythonbasics/blob/master/Numpy_DHien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from sympy import Matrix

def matran(n): #ham tao random ma tran a
    a = np.random.randint(low=10, size=(n, n))
    return a


def chuyen_vi(a): #ham tim ma tran chuyen vi cua ma tran a
    c = np.transpose(a)
    return c


def rank_matran(a): #ham tim rank cua ma tran a
    r = np.linalg.matrix_rank(a)
    return r


def bac_thang(a): #ham tim ma tran bac thang cua ma tran a
    a = Matrix(a)
    b = Matrix.rref(a)
    return np.array(b[0])


mt = np.array([[1, 2, 3],
               [2, 1, 3],
               [1, 1, 2]])
n = int(input("Nhap n: "))
a = matran(n) #ma tran random a
r = rank_matran(a) #rank cua ma tran a
b = bac_thang(a) #ma tran bac thang cua a
c = chuyen_vi(a) #ma tran chuyen vi cua a
don_vi = np.eye(3, 4)

print("Ma tran a: \n", a)
print("Ma tran mt: \n", mt)
print("Rank ma tran:", r)
print("Ma tran bac thang cua a: \n", b)
print("Ma tran chuyen vi cua a: \n", c)
print("Nhan 2 ma tran: \n", a@mt)
print("Cong 2 ma tran \n ", a+mt)
print("Tru 2 ma tran \n ", a-mt)
print("Ma tran don vi \n", don_vi)

Nhap n: 3
Ma tran a: 
 [[2 4 8]
 [0 4 5]
 [9 7 0]]
Ma tran mt: 
 [[1 2 3]
 [2 1 3]
 [1 1 2]]
Rank ma tran: 3
Ma tran bac thang cua a: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Ma tran chuyen vi cua a: 
 [[2 0 9]
 [4 4 7]
 [8 5 0]]
Nhan 2 ma tran: 
 [[18 16 34]
 [13  9 22]
 [23 25 48]]
Cong 2 ma tran 
  [[ 3  6 11]
 [ 2  5  8]
 [10  8  2]]
Tru 2 ma tran 
  [[ 1  2  5]
 [-2  3  2]
 [ 8  6 -2]]
Ma tran don vi 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
