<a href="https://colab.research.google.com/github/TranThiDieuHien/pythonbasics/blob/master/Numpy_Hien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
from sympy import Matrix
import random

def matran(n): #ham tao random ma tran a
    a = np.random.randint(low=10, size=(n, n))
    return a


def chuyen_vi(a): #ham tim ma tran chuyen vi cua ma tran a
    c = np.transpose(a)
    return c


def rank_matran(a): #ham tim rank cua ma tran a
    r = np.linalg.matrix_rank(a)
    return r


def bac_thang(a): #ham tim ma tran bac thang cua ma tran a
    a = Matrix(a)
    b = Matrix.rref(a)
    return np.array(b[0])


n = int(input("Nhap n: "))
a = matran(n) #ma tran random a
r = rank_matran(a) #rank cua ma tran a
b = bac_thang(a) #ma tran bac thang cua a
c = chuyen_vi(a) #ma tran chuyen vi cua a
don_vi = np.eye(3, 4)

print("Ma tran a: \n", a)
print("Rank ma tran:", r)
print("Ma tran bac thang cua a: \n", b)
print("Ma tran chuyen vi cua a: \n", c)
print("Nhan ma tran a voi ma tran a: \n", a@a)
print("Cong ma tran a voi a \n ", a+a)
print("Tru ma tran a voi a \n ", a-a)
print("Ma tran don vi \n", don_vi)

Nhap n: 4
Ma tran a: 
 [[4 1 9 8]
 [1 4 1 7]
 [5 4 1 7]
 [8 6 0 1]]
Rank ma tran: 4
Ma tran bac thang cua a: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Ma tran chuyen vi cua a: 
 [[4 1 5 8]
 [1 4 4 6]
 [9 1 1 0]
 [8 7 7 1]]
Nhan ma tran a voi ma tran a: 
 [[126  92  46 110]
 [ 69  63  14  50]
 [ 85  67  50  82]
 [ 46  38  78 107]]
Cong ma tran a voi a 
  [[ 8  2 18 16]
 [ 2  8  2 14]
 [10  8  2 14]
 [16 12  0  2]]
Tru ma tran a voi a 
  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Ma tran don vi 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
